### DISCUSSION TITLE
Logbook Spring Starter and Spring Cloud Starter Openfeign

### DISCUSSION THREAD

**Discussion by EvgDevt** [zalando/logbook#2098] [Q&A] [answered]
Hi!

I'm trying to figure out how to integrate logbook-spring-boot-starter with spring-cloud-starter-openfeign.

I've added the following dependencies:
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-web</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-openfeign</artifactId>
</dependency>

<dependency>
    <groupId>org.zalando</groupId>
    <artifactId>logbook-spring-boot-starter</artifactId>
    <version>3.12.0</version>
</dependency>

<!-- logbook openfeign support -->
<dependency>
    <groupId>org.zalando</groupId>
    <artifactId>logbook-openfeign</artifactId>
    <version>3.12.0</version>
</dependency>
```
The configuration (application.yml):
```
logbook:
  predicate:
    include:
      - path: /users
        methods:
          - GET
          - POST
      - path: /actuator/**
    exclude:
      - path: /api/admin/**
  filter.enabled: true
  secure-filter.enabled: true
  format.style: splunk
  obfuscate:
    headers:
      - Authorization
      - X-Secret
      - X-Auth-Token
      - password
    parameters:
      - access_token
      - password
    json-body-fields:
      - password
      - birthDate
    replacement: "[HIDDEN]"
  write:
    chunk-size: 1000
  attribute-extractors:
    - type: JwtFirstMatchingClaimExtractor
      claim-names: [ "sub", "subject" ]
      claim-key: Principal
    - type: JwtAllMatchingClaimsExtractor
      claim-names: [ "sub", "iat" ]

spring:
  application:
    name: Feign Demo
  cloud:
    openfeign:
      client:
        config:
          DemoFeignClientgetUserProfile:
            logger-level: FULL
            url: http://localhost:9090

logging:
  level:
    feign: debug
    org.zalando.logbook: trace
    dev.evg.feign.client: debug
```

Feign clients are engabled:
```
@SpringBootApplication
@EnableFeignClients
public class FeignDemoApplication {
    public static void main(String[] args) {
        SpringApplication.run(FeignDemoApplication.class, args);
    }
}
```

**Feign client**:
```
@FeignClient(name = "DemoFeignClient"
)
public interface DemoFeignClient {

    @GetMapping(path = "/api/user")
    UserResponse getUserProfile();
}
```

Simple rest controller for demo:
```
@RestController
@RequestMapping("/users")
public class DemoController {

    private final DemoService service;

    public DemoController(DemoService service) {
        this.service = service;
    }

    @GetMapping
    public UserResponse getUserProfile() {
        return service.getUser();
    }
}
```

And I don't see any logs from that feign client. Could you please guide me what I'm missing or maybe what I've done wrong.

Thank you in advance.
