### ISSUE TITLE
The body of request and response shown as {...} without details

### ISSUE THREAD

**Issue by DoneSpeak** [zalando/logbook#1317]
## Description

No body info show in the log.

Dependencies:
```xml
<dependency>
    <groupId>org.zalando</groupId>
    <artifactId>logbook-spring-boot-starter</artifactId>
    <version>2.14.0</version>
</dependency>
<dependency>
    <groupId>org.zalando</groupId>
    <artifactId>logbook-json</artifactId>
    <version>2.14.0</version>
</dependency>
```

Bean config:
```java
@Log4j2
@Configuration
public class LogBookConfig {

    @Bean
    public HeaderFilter authorizationHeaderFilter() {
        return headers -> {
            try {
                var userId = getCurrentUserId();
                var userIdStr = (userId == 0L? "no-userId": userId + "");
                return headers.update("authorization", userIdStr);
            } catch (Exception ex) {
                log.error("Fail to get userId from Context.", ex);
            }
            return headers;
        };
    }
}
```

config in yaml
```yml
logging.level.org.zalando.logbook: TRACE

logbook:
  include:
    - ${server.servlet.context-path}/v1/**
  exclude:
    - ${server.servlet.context-path}/v2/**
  filter.enabled: true
  secure-filter.enabled: true
  format.style: json
  strategy: body-only-if-status-at-least
  minimum-status: 200
  obfuscate:
    headers:
      - Authorization
      - X-Secret
      - postman-token
    parameters:
      - access_token
      - refresh_token
      - client_secret
      - password
      - email
      - mail
      - account
      - phone
  write:
    chunk-size: 10
    max-body-size: 1
```

The request log:
```
2022-04-14T03:43:34.853Z,[http-nio-8080-exec-1],TRACE,org.zalando.logbook.Logbook,21,{"origin":"remote","type":"request","correlation":"aedb10bddf61bd77","protocol":"HTTP/1.1","remote":"192.168.23.1","method":"GET","uri":"http://192.168.23.132:8080/api/v1/books/2","host":"192.168.23.132","path":"/api/v1/books/2","scheme":"http","port":"8080","headers":{"accept":["*/*"],"accept-encoding":["gzip, deflate, br"],"authorization":["55425103401"],"connection":["keep-alive"],"content-length":["2"],"content-type":["application/json"],"host":["192.168.23.132:8080"],"postman-token":["xxdfeseew-752-41ab-952e-103e2248218c6"],"user-agent":["PostmanRuntime/7.29.0"]},"body":{...}
2022-04-14T03:43:34.857Z,[http-nio-8080-exec-1],TRACE,org.zalando.logbook.Logbook,26,{"origin":"local","type":"response","correlation":"aedb10bddf61bd77","duration":272,"protocol":"HTTP/1.1","status":200,"headers":{"authorization":["10001"],"Cache-Control":["no-cache, no-store, max-age=0, must-revalidate"],"Connection":["keep-alive"],"Content-Type":["application/json;charset=UTF-8"],"Date":["Thu, 14 Apr 2022 03:43:34 GMT"],"Expires":["0"],"Keep-Alive":["timeout=60"],"Pragma":["no-cache"],"Transfer-Encoding":["chunked"],"Vary":["Origin","Access-Control-Request-Method","Access-Control-Request-Headers"],"X-Content-Type-Options":["nosniff"],"X-Frame-Options":["DENY"],"X-XSS-Protection":["1; mode=block"]},"body":{...}
````

## Expected Behavior

Show the real body content.

## Actual Behavior

The body of request and response shown as following:
```
{...}
```

**Comment by DoneSpeak** [comment]
If I add following bean, each line of the json body will be log as a single log instead of logging the whole json to one line.
```java
    @Bean
    public BodyFilter bodyFilter() {
        return (contentType, body) -> body;
    }
```

**Comment by DoneSpeak** [comment]
```yaml
  write:
    chunk-size: 10
    max-body-size: 1
```

limits the output
