### ISSUE TITLE
Zalando Logbook separate configuration from client and server side

### ISSUE THREAD

**Issue by honza-zidek** [zalando/logbook#2015]
Is it possible to configure Zalando Logbook separately for the **server side** logging (incoming requests) and the **client side** logging (outgoing requests)?

I'd like to log only some incoming requests (`/api/**` and `/int/**`), but all the outgoing requests not regarding their URI (`/**`).

Following the documentation https://gitee.com/kedocode/logbook#configuration, something like:

```yaml
logbook:
  server:
    predicate:
      include:
        - path: /api/**
        - path: /int/**
  client:
    predicate:
      include:
        - path: /**
```

The above configuration was the solution suggested by ChatGPT, but it doesn't seem to work, however the idea was good.
