### ISSUE TITLE
OutOfMemoryError produced by huge response, that must be excluded.

### ISSUE THREAD

**Issue by stavskiy** [zalando/logbook#315]
Hello!
I catch java.lang.OutOfMemoryError: Java heap space when I download huge text file (70 Mb) and response body become very big. This request (and response correspondingly) was excluded in property file and doesn't appear in log.
JVM params are -Xmx256m -Xms128m
I tried to use logbook.write.chunk-size with values 10 and 10000 - it didn't work.
Here is the error log: https://pastebin.com/ESTUwqZW
How can I avoid this exception?

* Version used: 1.9.0

**Comment by whiskeysierra** [comment]
What client are you using? Apache HTTP Client?

**Comment by stavskiy** [comment]
No, I'm using Spring RestController and download file by Postman. 
Stream from mongoDB goes to OutputStream of HttpServletResponse directly.

**Comment by whiskeysierra** [comment]
Ok, so you're responding from within your service. Can you show me your request and the logbook configuration?

**Comment by stavskiy** [comment]
Yes,
logbook configuration is: 

 ```
logbook:
 exclude:
  - /health
  - /v2/api-docs
  - /swagger-ui.html
  - /admin/**
  - /webjars/**
  - /swagger-resources/**
  - /etrack/exportArchive
obfuscate:
 headers:
   - Authorization
   - X-Secret
 parameters:
 - access_token
    - password
```

Request is:
`POST /etrack/exportArchive HTTP/1.1
Host: localhost:10731
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 389d800d-7459-06fe-03bb-afe6f5497d8f

{"startDate": "01/07/18", "startTime" : "00/00/00", "endDate": "15/07/18", "endTime" : "23/59/59"}`

**Comment by whiskeysierra** [comment]
Request is not visible in log, yet exception is still thrown?

**Comment by stavskiy** [comment]
Yes. When I disable logbook application works fine. I also tried to use LogbookBuilder and customized HeaderFilter, RawResponseFilter and BodyFilter, but it gave the same result.

**Comment by whiskeysierra** [comment]
Either your config is wrong or just incorrectly formatted. Can you verify?

**Comment by whiskeysierra** [comment]
Should look like this:

```yaml
logbook:
  exclude:
    - /etrack/exportArchive
```
