### ISSUE TITLE
Filter Logs by status code

### ISSUE THREAD

**Issue by LimaIsaias** [zalando/logbook#521]
Forgive me for writing my English, I'm using google translate.
I would like to be able to filter and just print the logs where the response status is 4XX or 5XX, is it possible? and if so, how can I implement it?

**Comment by whiskeysierra** [comment]
## Programmatic

```java
Logbook.builder()
    .strategy(new StatusAtLeastStrategy(400))
    .build();
```

## Spring Boot Auto Configuration

```yaml
logbook:
  strategy: status-at-least
  minimum-status: 400
```
