### ISSUE TITLE
doc | document mistake in Example Configuration.

### ISSUE THREAD

**Issue by DoneSpeak** [zalando/logbook#923]
## Description

There is a document mistake in [Example Configuration](https://github.com/zalando/logbook#example-configuration).

```yml
logbook:
  include:
    - /api/**
    - /actuator/**
  exclude:
    - /actuator/health
    - /api/admin/**
  filter.enabled: true
  secure-filter.enabled: true
  format.style: http
  strategy: body-only-if-status-at-least
  minimum-status: 400
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
    # Here is the mistake.
    write:
      chunk-size: 1000
```

## Expected Behavior

```yml
logbook:
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
    # Here is the mistake.
  write:
    chunk-size: 1000
```
