### ISSUE TITLE
logbook configuration file

### ISSUE THREAD

**Issue by moorsu** [zalando/logbook#935]
I am using Spring Boot application.  I would like to keep the following configurations in a file.  I tried in src/main/resources/logbook.yml, src/main/resources/application.yml.  But the changes are not reflected in the logging. 

Please help

```
logbook:
  include:
    - /api/**
    - /actuator/**
  exclude:
    - /actuator/health
    - /api/admin/**
  filter.enabled: true
  secure-filter.enabled: true
  format.style: http
  strategy: body-only-if-status-at-least
  minimum-status: 400
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  write:
    chunk-size: 1000
```
